### ISSUE TITLE
How do I set the gravity of the timer text to center? 

### ISSUE THREAD

**Issue by haldertaer** [BCGDV-ASIA/android-widget-ticktock#6]
How do I set the gravity of the timer text to center?  Currently, the timer automatically aligns left - I'd like to center the text!

![_](https://cloud.githubusercontent.com/assets/26697617/25503600/a16d352c-2ba3-11e7-9411-ab382c47191e.png)
As you can see above, the alignment is to the left by default.

**Comment by haldertaer** [comment]
I'm still waiting for an answer :)

**Comment by baadillahnabil** [comment]
set initial text in xml like this : (it worked for me in Android M)
app:tickText="00h:00m:00s"

as raylenmoore said in here : https://github.com/BCGDV-ASIA/android-widget-ticktock/issues/1

**Comment by haldertaer** [comment]
@baadillahnabil this is not enough when the countdown is only in seconds (which is my case). after it reaches 9 seconds there is only one digit. And it displays as in the picture I posted.

**Comment by baadillahnabil** [comment]
@haldertaer 
how about add "0" in front of every 1 digit number ? so all the number have 2 digits ?

if you still want to display 1 digit only, then i would suggest you to create new regular `textview` and place it in the center of "ticktock-circle" and set that `textview` text inside `onTickListener()`

i use custom textview too because i want to change font style and customize it little bit which i don't know how if i used default textview provided by this library 
and it worked for me :)

**Comment by haldertaer** [comment]
This isn't really efficient... @alphamu Can you please reply?

**Comment by alphamu** [comment]
This has been a while and I'll have to check the code, however as an "optimisation" I don't layout measure and layout the text on every tick. I can check and update the widget in a few days, for now I would recommend that if you can tolerate this, don't display any text in the widget, instead wrap it in a frame layout with a textview and which you can update on each tick.

**Comment by haldertaer** [comment]
@alphamu I'll wait for the update for a few days then. Thanks!

**Comment by alphamu** [comment]
I've just published `v1.3`, if you update your library to it, it should hopefully fix the issue.
The fix is quick and dirty, simply if the text length (in terms of characters) changes, I measure the text bounds again. This should fix the issue of going for "10 s" to "9 s" and the text appearing left aligned. @haldertaer if this fixes the issue, please close the ticket.

**Comment by haldertaer** [comment]
Appreciate it @alphamu ! Very nice widget, good job!

**Comment by haldertaer** [comment]
I'll try it tomorrow.

**Comment by haldertaer** [comment]
I'll try it tomorrow and inform you @alphamu

**Comment by haldertaer** [comment]
Great work @alphamu The timer text is now centered. The issue has been fixed, I'll now close it.
